//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOB.ESG.FRONT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UOB.ESG.FRONT.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At UOB Asset Management (UOBAM), our vision is to be a leading fund manager in sustainability in Asia that creates long-term value and positive impact for our stakeholders whilst enabling sustainable investments accessible for all.
        ///As an active asset manager, UOBAM believes that it has a fiduciary duty to allocate capital into more sustainable investments and be active owners of our investments and as a signatory to the United Nations Principles for Responsible Investment (PRI), we are committed to adoptin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string appoach_detail1 {
            get {
                return ResourceManager.GetString("appoach_detail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (a) where administrative or other procedures result in the costs of voting outweighing the benefits;
        ///(b) the voting securities are part of a securities lending program and UOBAM is unable to vote securities that are out on loan;
        ///(c) a meeting notice is delivered close to the meeting date and UOBAM has insufficient time to adequately assess the issues being tabled at the shareholders’ meeting and / or process the vote;
        ///(d) UOBAM sells shares prior to a company&apos;s meeting date and decides not to vote those  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string appoach_detail10 {
            get {
                return ResourceManager.GetString("appoach_detail10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string appoach_detail11 {
            get {
                return ResourceManager.GetString("appoach_detail11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our sustainability governance structure provides oversight and accountability on the implementation of our responsible investment policy. Our UOBAM Board of directors through the Management Committee (MC), reviews long-term business and organisational goals and provides the strategic direction for UOBAM’s sustainable investments and sustainability practices. The MC manages the implementation of strategic direction that is handed down by UOBAM’s Board of Directors and will be supported by our Regional Sustai [rest of string was truncated]&quot;;.
        /// </summary>
        public static string appoach_detail12 {
            get {
                return ResourceManager.GetString("appoach_detail12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We take an inside-out approach to sustainable investing and move beyond just focusing on internal processes such as ESG integration into investment processes and sustainable investment governance. We look to take a proactive approach towards driving sustainable investing externally which ties in closely with the principle of “working together in implementing the principles” where our external efforts include establishing strategic investment partnerships with global sustainability leaders such as Robeco and [rest of string was truncated]&quot;;.
        /// </summary>
        public static string appoach_detail13 {
            get {
                return ResourceManager.GetString("appoach_detail13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In our commitment towards advancing and supporting the principles of PRI, we have put in place our sustainable investing policy as part of our sustainable investment framework, as set out in the table below..
        /// </summary>
        public static string appoach_detail2 {
            get {
                return ResourceManager.GetString("appoach_detail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We believe that Environmental, Social, and Governance (ESG) issues are financially material to a company’s performance and will translate to material financial impact on the investments that we make. As part of our fiduciary duty to our investors, we have put in place our sustainable investing framework and process which focuses on deep fundamental research, augmented by the use of technology and leveraging on our local expertise. &lt;br&gt; Our proprietary sustainable investment framework is a common framework t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string appoach_detail3 {
            get {
                return ResourceManager.GetString("appoach_detail3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The execution of ESG evaluation and integration into our investment process is supported by dedicated resources in our regional investment teams and covering all major asset classes that we invest in. Overall, we believe that ESG integration into our investment process contributes to performance and risk mitigation by enabling us to identify high-quality companies which are resilient, well-managed, able to grow sustainably and are likely to maintain their competitiveness in the long term..
        /// </summary>
        public static string appoach_detail4 {
            get {
                return ResourceManager.GetString("appoach_detail4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To complement ESG incorporation into our investment process, we also have in place an Active Ownership Policy which has a coverage that aligns to the Sustainable Investment Policy. The Active Ownership Policy serves to facilitate dialogue, engagement, and proxy voting. We will leverage our regional footprint and the local expertise of our regional investment teams to execute meaningful dialogues and engagement which will drive strategic investment decisions for the sustainable investments we make.
        ///To quant [rest of string was truncated]&quot;;.
        /// </summary>
        public static string appoach_detail5 {
            get {
                return ResourceManager.GetString("appoach_detail5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustainability is a key pillar in UOB Asset Management’s (UOBAM) corporate strategy, and we view active ownership is a crucial aspect of our sustainability culture, as it can positively influence companies to engage in sustainable business practices, creating not only long-term value for these companies but also social and environmental benefits for the world.
        ///
        ///We have a strong regard for fostering good stewardship and as an asset manager based in Singapore, we are a signatory to our local stewardship cod [rest of string was truncated]&quot;;.
        /// </summary>
        public static string appoach_detail6 {
            get {
                return ResourceManager.GetString("appoach_detail6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOBAM believes in the value of engagement and aim to enhance risk-adjusted returns of our investments and shareholders’ value in the long run. We identify a range of thematic and material ESG issues that can affect our investee companies in the long run and engage them to ensure that they are well prepared to mitigate these issues.
        ///Throughout the engagement process, we gain valuable insights into our investee companies’ propensity deal with ESG issues and whether they will take the appropriate measures to  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string appoach_detail7 {
            get {
                return ResourceManager.GetString("appoach_detail7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOBAM aims to vote on the vast majority of proposals raised at every company meeting in a timely manner. UOBAM has engaged the services of proxy voting agent, Institutional Shareholder Services Inc. (“ISS”) to provide us with proxy voting services and proxy voting research and recommendations.
        ///While UOBAM has authorised ISS to vote on its behalf, UOBAM retains full discretion over all voting decisions and reserves the right to vote contrary to the recommendations of ISS. This can occur when UOBAM have a di [rest of string was truncated]&quot;;.
        /// </summary>
        public static string appoach_detail8 {
            get {
                return ResourceManager.GetString("appoach_detail8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over the course of the engagement process, UOBAM would pursue a number of courses of action should the company constantly fails to meet the standards expected.
        ///UOBAM will vote against management at the annual company meetings if we are not satisfied with managements’ response to the ESG issues raised and ability to mitigate the identified risks. UOBAM may also consider voting for shareholder resolutions initiated in response to the ESG issues.
        ///Ultimately, if the company still continuously fails to meet th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string appoach_detail9 {
            get {
                return ResourceManager.GetString("appoach_detail9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/appoach-m/1-th-mobile.png.
        /// </summary>
        public static string appoach_m_1 {
            get {
                return ResourceManager.GetString("appoach_m_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/appoach-m/2-th-mobile.png.
        /// </summary>
        public static string appoach_m_2 {
            get {
                return ResourceManager.GetString("appoach_m_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/appoach-m/3-th-mobile.png.
        /// </summary>
        public static string appoach_m_3 {
            get {
                return ResourceManager.GetString("appoach_m_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOBAM’S Sustainable Investing Vision and Goals.
        /// </summary>
        public static string appoach_sub_title1 {
            get {
                return ResourceManager.GetString("appoach_sub_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOBAM’s Sustainable Investing Governance Structure.
        /// </summary>
        public static string appoach_sub_title10 {
            get {
                return ResourceManager.GetString("appoach_sub_title10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Nations-supported Principles for Responsible Investment (PRI).
        /// </summary>
        public static string appoach_sub_title11 {
            get {
                return ResourceManager.GetString("appoach_sub_title11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOBAM’s Approach to Strategic Partnerships.
        /// </summary>
        public static string appoach_sub_title13 {
            get {
                return ResourceManager.GetString("appoach_sub_title13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOBAM’s Sustainable Investment Framework.
        /// </summary>
        public static string appoach_sub_title2 {
            get {
                return ResourceManager.GetString("appoach_sub_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOBAM Active Ownership Approach.
        /// </summary>
        public static string appoach_sub_title6 {
            get {
                return ResourceManager.GetString("appoach_sub_title6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Voting.
        /// </summary>
        public static string appoach_sub_title7 {
            get {
                return ResourceManager.GetString("appoach_sub_title7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investing for profit and purpose.
        /// </summary>
        public static string appoach_sub_title9 {
            get {
                return ResourceManager.GetString("appoach_sub_title9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustainable Investment and Active Ownership Approach.
        /// </summary>
        public static string appoach_title {
            get {
                return ResourceManager.GetString("appoach_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Engagement.
        /// </summary>
        public static string btn_header1 {
            get {
                return ResourceManager.GetString("btn_header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More &gt;&gt;.
        /// </summary>
        public static string btn_read_more {
            get {
                return ResourceManager.GetString("btn_read_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning: investments are risky, investors should understand the characteristics of the fund,
        ///fund policy, return conditions, risk and performance of the fund before 
        ///making an investment decision. past performance/comparison of performance 
        ///related to capital markets products it is not a confirmation of future performance. 
        ///investment is risked by exchange rates that may arise from foreign 
        ///investment. although the fund may hedge at the discretion of the mutual fund
        ///manager, because the fund does not  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string footer_condition {
            get {
                return ResourceManager.GetString("footer_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello-123.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/appoach-m/1-en-desktop.png.
        /// </summary>
        public static string img_artwork_1 {
            get {
                return ResourceManager.GetString("img_artwork_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/appoach/EN/2.png.
        /// </summary>
        public static string img_artwork_2 {
            get {
                return ResourceManager.GetString("img_artwork_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/appoach/EN/3.png.
        /// </summary>
        public static string img_artwork_3 {
            get {
                return ResourceManager.GetString("img_artwork_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/appoach/EN/4.png.
        /// </summary>
        public static string img_artwork_4 {
            get {
                return ResourceManager.GetString("img_artwork_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/appoach/EN/5.png.
        /// </summary>
        public static string img_artwork_5 {
            get {
                return ResourceManager.GetString("img_artwork_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/appoach/EN/2_Mobile.png.
        /// </summary>
        public static string img_artwork_m_2 {
            get {
                return ResourceManager.GetString("img_artwork_m_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/appoach/EN/3_Mobile.png.
        /// </summary>
        public static string img_artwork_m_3 {
            get {
                return ResourceManager.GetString("img_artwork_m_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/appoach/EN/4_Mobile.png.
        /// </summary>
        public static string img_artwork_m_4 {
            get {
                return ResourceManager.GetString("img_artwork_m_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/appoach/EN/5_Mobile.png.
        /// </summary>
        public static string img_artwork_m_5 {
            get {
                return ResourceManager.GetString("img_artwork_m_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/appoach/EN/5.png.
        /// </summary>
        public static string img_artwork_m_6 {
            get {
                return ResourceManager.GetString("img_artwork_m_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start investing today Start your investment to grow
        ///to achieve financial objectives effectively.
        /// </summary>
        public static string port_title {
            get {
                return ResourceManager.GetString("port_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustainability is about meeting the  &lt;br /&gt; needs of the present generation without compromising the ability of future generations to meet theirs..
        /// </summary>
        public static string section_1_menu_1_text {
            get {
                return ResourceManager.GetString("section_1_menu_1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doing Well by Doing Good.
        /// </summary>
        public static string section_1_menu_1_title {
            get {
                return ResourceManager.GetString("section_1_menu_1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustainable investing balances traditional investing fundamentals with environmental, social, and governance (ESG).
        /// </summary>
        public static string section_1_menu_2_text {
            get {
                return ResourceManager.GetString("section_1_menu_2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investing for Profit and Purpose.
        /// </summary>
        public static string section_1_menu_2_title {
            get {
                return ResourceManager.GetString("section_1_menu_2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our technological edge in ESG integration lies in augmentation with
        ///The support of Artificial Intelligence-
        ///Machine Learning (AI-ML).
        /// </summary>
        public static string section_1_menu_3_text {
            get {
                return ResourceManager.GetString("section_1_menu_3_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Edge in Sustainable Investing.
        /// </summary>
        public static string section_1_menu_3_title {
            get {
                return ResourceManager.GetString("section_1_menu_3_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying sustainable development &lt;br /&gt;  principles to financial investments, taking ESG factors into account.
        /// </summary>
        public static string section_1_text {
            get {
                return ResourceManager.GetString("section_1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT IS SUSTAINABLE &lt;br /&gt; INVESTING?.
        /// </summary>
        public static string section_1_title {
            get {
                return ResourceManager.GetString("section_1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In recent years, the importance of sustainability has been rapidly increasing. At UOBAM, we recognise that we have an important role to play as socially responsible stewards to drive sustainability in the world.
        /// 
        ///The investment community has a key role to play in supporting sustainability and the growing emphasis on environmental, social and governance (ESG) issues by channelling capital into sustainable opportunities, while supporting the United Nations Sustainable Development Goals (UN SDGs).
        /// 
        ///Asset [rest of string was truncated]&quot;;.
        /// </summary>
        public static string section_2_ceo_history {
            get {
                return ResourceManager.GetString("section_2_ceo_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the past few years, the concept of sustainable corporate development or ESG which stands for Environment, Social and Governance are based on the fact that business operations interact with environment and human social life which has grown in popularity. Hence, to balance how the businesses co-exist with the environment and society, companies could enhance and sustaining their profitability. This includes incorporating the ESG concept in investments to which the investors have been increasingly pay attent [rest of string was truncated]&quot;;.
        /// </summary>
        public static string section_2_ceo_history1 {
            get {
                return ResourceManager.GetString("section_2_ceo_history1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thio Boon Kiat.
        /// </summary>
        public static string section_2_ceo_name {
            get {
                return ResourceManager.GetString("section_2_ceo_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vana Bulbon.
        /// </summary>
        public static string section_2_ceo_name1 {
            get {
                return ResourceManager.GetString("section_2_ceo_name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group CEO of UOB Asset Management
        ///UOBAM (Thailand).
        /// </summary>
        public static string section_2_ceo_position {
            get {
                return ResourceManager.GetString("section_2_ceo_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Executive Officer
        ///UOBAM (Thailand).
        /// </summary>
        public static string section_2_ceo_position1 {
            get {
                return ResourceManager.GetString("section_2_ceo_position1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At UOB Asset Management (UOBAM), our vision is to be a leading fund manager in sustainability in Asia that creates long - term value and positive impact for our stakeholders whilst enabling sustainable investments accessible for all..
        /// </summary>
        public static string section_3_text {
            get {
                return ResourceManager.GetString("section_3_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOBAM’S SUSTAINABLE  &lt;br /&gt; INVESTMENT APPROACH.
        /// </summary>
        public static string section_3_title {
            get {
                return ResourceManager.GetString("section_3_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda.
        /// </summary>
        public static string section_4_text {
            get {
                return ResourceManager.GetString("section_4_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article &amp; Activity.
        /// </summary>
        public static string section_4_title {
            get {
                return ResourceManager.GetString("section_4_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae Vitae dicta sunt explicabo..
        /// </summary>
        public static string section_5_text {
            get {
                return ResourceManager.GetString("section_5_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUSTAINABILITY IS THE ONE OF MEGATREND.
        /// </summary>
        public static string section_5_title {
            get {
                return ResourceManager.GetString("section_5_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT IS SUSTAINABLE INVESTING?.
        /// </summary>
        public static string section_menu_1 {
            get {
                return ResourceManager.GetString("section_menu_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Commitment.
        /// </summary>
        public static string section_menu_2 {
            get {
                return ResourceManager.GetString("section_menu_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOBAM’S Sustainable &lt;br /&gt;Investment Approach.
        /// </summary>
        public static string section_menu_3 {
            get {
                return ResourceManager.GetString("section_menu_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article &amp; Activity.
        /// </summary>
        public static string section_menu_4 {
            get {
                return ResourceManager.GetString("section_menu_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustainability Solution.
        /// </summary>
        public static string section_menu_5 {
            get {
                return ResourceManager.GetString("section_menu_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While UOBAM has authorised ISS to vote on its behalf, UOBAM retains full discretion over all voting decisions and reserves the right to vote contrary to the recommendations of ISS. This can occur when UOBAM have a differing view that these vote recommendations are not in the best interest of its clients, after taking into account relevant information in its decision e.g. engagement outcome, internal research, etc..
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have a strong regard for fostering good stewardship and as an asset manager based in Singapore, we are a signatory to our local stewardship code (Singapore Stewardship Principles (SSP) for Responsible Investors). UOBAM is also a signatory of the UN supported Principles for Responsible Investment (PRI), and we are committed to follow their 6 Principles..
        /// </summary>
        public static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active ownership at UOBAM consists of company engagement and proxy voting activities. These activities form a key component of our responsible investment approach and fulfils UOBAM’s fiduciary duty as an investment manager to act in the best long-term interests of our clients..
        /// </summary>
        public static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We take an inside-out approach to sustainable investing and move beyond just focusing on internal processes such as ESG integration into investment processes and sustainable investment governance. We look to take a proactive approach towards driving sustainable investing externally which ties in closely with the principle of “working together in implementing the principles” where our external efforts include establishing strategic investment partnerships with global sustainability leaders such as Robeco and [rest of string was truncated]&quot;;.
        /// </summary>
        public static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Through such external partnerships that we aim to further enhance our capabilities and develop the accessibility of sustainability investment opportunities in the Asia region for investors. This will be done through sustainability mandates, working in policy consultation, and responsible investment education and thought leadership..
        /// </summary>
        public static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There may be situations where UOBAM may choose not to vote or abstain from voting:.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (a) where administrative or other procedures result in the costs of voting outweighing the benefits;.
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (b) the voting securities are part of a securities lending program and UOBAM is unable to vote securities that are out on loan;.
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (c) a meeting notice is delivered close to the meeting date and UOBAM has insufficient time to adequately assess the issues being tabled at the shareholders’ meeting and / or process the vote;.
        /// </summary>
        public static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (d) UOBAM sells shares prior to a company&apos;s meeting date and decides not to vote those shares, on the basis that UOBAM shall not be restricted from trading in a security due to an upcoming shareholder meeting; and.
        /// </summary>
        public static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (e) voting securities have been blocked from trading in order to be tendered for voting purposes and UOBAM believes that preserving the ability to trade the security is in the best interest of the beneficiaries;.
        /// </summary>
        public static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (f) in event of a situation where regulatory obligations and rulings of the SIC imposed on UOB Group that also apply to UOBAM, may prohibit UOBAM from voting on securities due to its deemed affiliation for a corporate action..
        /// </summary>
        public static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustainability is a key pillar in UOB Asset Management’s (UOBAM) corporate strategy, and we view active ownership is a crucial aspect of our sustainability culture, as it can positively influence companies to engage in sustainable business practices, creating not only long-term value for these companies but also social and environmental benefits for the world..
        /// </summary>
        public static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
    }
}
