//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOB.PVD.FRONT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UOB.PVD.FRONT.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provident Fund.
        /// </summary>
        public static string banner_title {
            get {
                return ResourceManager.GetString("banner_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/chart/desktop/chart-en.png.
        /// </summary>
        public static string img_chart_desktop {
            get {
                return ResourceManager.GetString("img_chart_desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/chart/mobile/en/1.png.
        /// </summary>
        public static string img_chart_mobile_1 {
            get {
                return ResourceManager.GetString("img_chart_mobile_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/chart/mobile/en/10.png.
        /// </summary>
        public static string img_chart_mobile_10 {
            get {
                return ResourceManager.GetString("img_chart_mobile_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/chart/mobile/en/11.png.
        /// </summary>
        public static string img_chart_mobile_11 {
            get {
                return ResourceManager.GetString("img_chart_mobile_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/chart/mobile/en/12.png.
        /// </summary>
        public static string img_chart_mobile_12 {
            get {
                return ResourceManager.GetString("img_chart_mobile_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/chart/mobile/en/13.png.
        /// </summary>
        public static string img_chart_mobile_13 {
            get {
                return ResourceManager.GetString("img_chart_mobile_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/chart/mobile/en/14.png.
        /// </summary>
        public static string img_chart_mobile_14 {
            get {
                return ResourceManager.GetString("img_chart_mobile_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/chart/mobile/en/15.png.
        /// </summary>
        public static string img_chart_mobile_15 {
            get {
                return ResourceManager.GetString("img_chart_mobile_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/chart/mobile/en/2.png.
        /// </summary>
        public static string img_chart_mobile_2 {
            get {
                return ResourceManager.GetString("img_chart_mobile_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/chart/mobile/en/3.png.
        /// </summary>
        public static string img_chart_mobile_3 {
            get {
                return ResourceManager.GetString("img_chart_mobile_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/chart/mobile/en/4.png.
        /// </summary>
        public static string img_chart_mobile_4 {
            get {
                return ResourceManager.GetString("img_chart_mobile_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/chart/mobile/en/5.png.
        /// </summary>
        public static string img_chart_mobile_5 {
            get {
                return ResourceManager.GetString("img_chart_mobile_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/chart/mobile/en/6.png.
        /// </summary>
        public static string img_chart_mobile_6 {
            get {
                return ResourceManager.GetString("img_chart_mobile_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/chart/mobile/en/7.png.
        /// </summary>
        public static string img_chart_mobile_7 {
            get {
                return ResourceManager.GetString("img_chart_mobile_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/chart/mobile/en/8.png.
        /// </summary>
        public static string img_chart_mobile_8 {
            get {
                return ResourceManager.GetString("img_chart_mobile_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/chart/mobile/en/9.png.
        /// </summary>
        public static string img_chart_mobile_9 {
            get {
                return ResourceManager.GetString("img_chart_mobile_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pooled funds under.
        /// </summary>
        public static string Index_Message_1 {
            get {
                return ResourceManager.GetString("Index_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A master pooled fund with carefully constructed seven pre-defined allocations to three underlying mutual funds which represent each core asset class. Fund members are able to select one of the seven investment plans, or as per the condition that the fund committee set forth in the fund regulation.
        ///The fund won the 6th Provident Fund Award 2017 “Pooled Fund – fund size less than 10,000 Million Baht” from The Securities and Exchange Commission, Thailand (SEC).
        /// </summary>
        public static string Index_Message_10 {
            get {
                return ResourceManager.GetString("Index_Message_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Index_Message_11 {
            get {
                return ResourceManager.GetString("Index_Message_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Index_Message_12 {
            get {
                return ResourceManager.GetString("Index_Message_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Index_Message_13 {
            get {
                return ResourceManager.GetString("Index_Message_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCAL.
        /// </summary>
        public static string Index_Message_14 {
            get {
                return ResourceManager.GetString("Index_Message_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLOBAL.
        /// </summary>
        public static string Index_Message_15 {
            get {
                return ResourceManager.GetString("Index_Message_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOB Investor Choice Registered Provident Fund.
        /// </summary>
        public static string Index_Message_16 {
            get {
                return ResourceManager.GetString("Index_Message_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defensive.
        /// </summary>
        public static string Index_Message_17 {
            get {
                return ResourceManager.GetString("Index_Message_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth 10.
        /// </summary>
        public static string Index_Message_18 {
            get {
                return ResourceManager.GetString("Index_Message_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth 20.
        /// </summary>
        public static string Index_Message_19 {
            get {
                return ResourceManager.GetString("Index_Message_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to management of UOBAM 
        ///(Thailand).
        /// </summary>
        public static string Index_Message_2 {
            get {
                return ResourceManager.GetString("Index_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth 40.
        /// </summary>
        public static string Index_Message_20 {
            get {
                return ResourceManager.GetString("Index_Message_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth 15.
        /// </summary>
        public static string Index_Message_21 {
            get {
                return ResourceManager.GetString("Index_Message_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SustainableGrowth 60.
        /// </summary>
        public static string Index_Message_22 {
            get {
                return ResourceManager.GetString("Index_Message_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth 60.
        /// </summary>
        public static string Index_Message_23 {
            get {
                return ResourceManager.GetString("Index_Message_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth 80.
        /// </summary>
        public static string Index_Message_24 {
            get {
                return ResourceManager.GetString("Index_Message_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth 100.
        /// </summary>
        public static string Index_Message_25 {
            get {
                return ResourceManager.GetString("Index_Message_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defensive.
        /// </summary>
        public static string Index_Message_26 {
            get {
                return ResourceManager.GetString("Index_Message_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth 10.
        /// </summary>
        public static string Index_Message_27 {
            get {
                return ResourceManager.GetString("Index_Message_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth 20.
        /// </summary>
        public static string Index_Message_28 {
            get {
                return ResourceManager.GetString("Index_Message_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth 40.
        /// </summary>
        public static string Index_Message_29 {
            get {
                return ResourceManager.GetString("Index_Message_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pooled funds under management of UOB Asset
        ///Management(Thailand) Co., Ltd. are Master Pooled
        ///Fund under which the fund members are allowed
        ///to select investment plan that matches with their
        ///risk appetite and retirement goal, varied by age,
        ///investment horizon, investment knowledge,
        ///expected return or acceptable risk level..
        /// </summary>
        public static string Index_Message_3 {
            get {
                return ResourceManager.GetString("Index_Message_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth 15.
        /// </summary>
        public static string Index_Message_30 {
            get {
                return ResourceManager.GetString("Index_Message_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustainable Growth 60.
        /// </summary>
        public static string Index_Message_31 {
            get {
                return ResourceManager.GetString("Index_Message_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth 60.
        /// </summary>
        public static string Index_Message_32 {
            get {
                return ResourceManager.GetString("Index_Message_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth 80.
        /// </summary>
        public static string Index_Message_33 {
            get {
                return ResourceManager.GetString("Index_Message_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth 100.
        /// </summary>
        public static string Index_Message_34 {
            get {
                return ResourceManager.GetString("Index_Message_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic Money Market: TCMFPVD*.
        /// </summary>
        public static string Index_Message_35 {
            get {
                return ResourceManager.GetString("Index_Message_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic Fixed Income: TFIFPVD*.
        /// </summary>
        public static string Index_Message_36 {
            get {
                return ResourceManager.GetString("Index_Message_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic Equity: TEF*.
        /// </summary>
        public static string Index_Message_37 {
            get {
                return ResourceManager.GetString("Index_Message_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Short-Term fixed income: UFFF-I*.
        /// </summary>
        public static string Index_Message_38 {
            get {
                return ResourceManager.GetString("Index_Message_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Fixed Income: USI*.
        /// </summary>
        public static string Index_Message_39 {
            get {
                return ResourceManager.GetString("Index_Message_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOBAM (Thailand) offers the following master pooled funds:.
        /// </summary>
        public static string Index_Message_4 {
            get {
                return ResourceManager.GetString("Index_Message_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Equity: UESG*.
        /// </summary>
        public static string Index_Message_40 {
            get {
                return ResourceManager.GetString("Index_Message_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Balanced Fund: UGBF-N*.
        /// </summary>
        public static string Index_Message_41 {
            get {
                return ResourceManager.GetString("Index_Message_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Policy of each underlying mutual fund.
        /// </summary>
        public static string Index_Message_42 {
            get {
                return ResourceManager.GetString("Index_Message_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UGBF-N:.
        /// </summary>
        public static string Index_Message_43 {
            get {
                return ResourceManager.GetString("Index_Message_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feeder to JPMorgan Investment Funds – Global Balanced Fund class: JPM Global Balanced C (acc) - USD (hedged) at least 80% of NAV. The Master Fund objective is to create the regular income in long term..
        /// </summary>
        public static string Index_Message_44 {
            get {
                return ResourceManager.GetString("Index_Message_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UFFF-I:.
        /// </summary>
        public static string Index_Message_45 {
            get {
                return ResourceManager.GetString("Index_Message_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invest in foreign bond mutual funds and / or exchange-traded fund (ETF) and / or mutual funds under management of UOBAM.
        /// </summary>
        public static string Index_Message_46 {
            get {
                return ResourceManager.GetString("Index_Message_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USI:.
        /// </summary>
        public static string Index_Message_47 {
            get {
                return ResourceManager.GetString("Index_Message_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feeder to RobecoSAM SDG Credit Income IH USD to maintain consistent income by investing in a variety of debt instruments under UN Sustainable Development GoalsSDGs.
        /// </summary>
        public static string Index_Message_48 {
            get {
                return ResourceManager.GetString("Index_Message_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UESG:.
        /// </summary>
        public static string Index_Message_49 {
            get {
                return ResourceManager.GetString("Index_Message_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. UOB Investor Choice Registered Provident Fund
        ///2. UOB Master Fund Registered Provident Fund.
        /// </summary>
        public static string Index_Message_5 {
            get {
                return ResourceManager.GetString("Index_Message_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feeder to Robeco Sustainable Global Stars Equities IL EUR.
        /// </summary>
        public static string Index_Message_50 {
            get {
                return ResourceManager.GetString("Index_Message_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Index_Message_51 {
            get {
                return ResourceManager.GetString("Index_Message_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. UOB Master Fund Registered Provident Fund.
        /// </summary>
        public static string Index_Message_52 {
            get {
                return ResourceManager.GetString("Index_Message_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another master pooled fund with a variety of investment policies, which either invest directly in financial instruments or via mutual funds. The fund committee determines the investment options to be made available to the fund members, or allows the members to freely choose a desired mix of investment policies by themselves (Do It Yourself: DIY)..
        /// </summary>
        public static string Index_Message_53 {
            get {
                return ResourceManager.GetString("Index_Message_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCAL.
        /// </summary>
        public static string Index_Message_54 {
            get {
                return ResourceManager.GetString("Index_Message_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLOBAL.
        /// </summary>
        public static string Index_Message_55 {
            get {
                return ResourceManager.GetString("Index_Message_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOB Investor Choice Registered Provident Fund.
        /// </summary>
        public static string Index_Message_56 {
            get {
                return ResourceManager.GetString("Index_Message_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Remark :
        ///Investment Policy 1-4 = direct investment
        ///Other Investment Policy = invest through mutual funds.
        /// </summary>
        public static string Index_Message_57 {
            get {
                return ResourceManager.GetString("Index_Message_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Index_Message_58 {
            get {
                return ResourceManager.GetString("Index_Message_58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Index_Message_59 {
            get {
                return ResourceManager.GetString("Index_Message_59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. UOB Investor Choice Registered Provident Fund.
        /// </summary>
        public static string Index_Message_6 {
            get {
                return ResourceManager.GetString("Index_Message_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Index_Message_60 {
            get {
                return ResourceManager.GetString("Index_Message_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Index_Message_61 {
            get {
                return ResourceManager.GetString("Index_Message_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. UOB Master Fund Registered Provident Fund.
        /// </summary>
        public static string Index_Message_7 {
            get {
                return ResourceManager.GetString("Index_Message_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. UOB Investor Choice Registered Provident Fund.
        /// </summary>
        public static string Index_Message_8 {
            get {
                return ResourceManager.GetString("Index_Message_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Index_Message_9 {
            get {
                return ResourceManager.GetString("Index_Message_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string menu_item_1 {
            get {
                return ResourceManager.GetString("menu_item_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string menu_item_2 {
            get {
                return ResourceManager.GetString("menu_item_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string menu_item_3 {
            get {
                return ResourceManager.GetString("menu_item_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        public static string menu_item_4 {
            get {
                return ResourceManager.GetString("menu_item_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVD Fact Sheet.
        /// </summary>
        public static string menu_item_5 {
            get {
                return ResourceManager.GetString("menu_item_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Profile.
        /// </summary>
        public static string menu_item_6 {
            get {
                return ResourceManager.GetString("menu_item_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string menu_item_7 {
            get {
                return ResourceManager.GetString("menu_item_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string menu_item_8 {
            get {
                return ResourceManager.GetString("menu_item_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string menu_item_9 {
            get {
                return ResourceManager.GetString("menu_item_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVD Fact Sheet.
        /// </summary>
        public static string Sheet_Message_1 {
            get {
                return ResourceManager.GetString("Sheet_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your personal portfolio with recommended mutual funds.
        /// </summary>
        public static string Sheet_Message_10 {
            get {
                return ResourceManager.GetString("Sheet_Message_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Fund: Megatrend SSF.
        /// </summary>
        public static string Sheet_Message_11 {
            get {
                return ResourceManager.GetString("Sheet_Message_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Fund: Megatrend RMF.
        /// </summary>
        public static string Sheet_Message_12 {
            get {
                return ResourceManager.GetString("Sheet_Message_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your post-retirement portfolio.
        /// </summary>
        public static string Sheet_Message_13 {
            get {
                return ResourceManager.GetString("Sheet_Message_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Policy of each underlying mutual fund.
        /// </summary>
        public static string Sheet_Message_14 {
            get {
                return ResourceManager.GetString("Sheet_Message_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Sheet_Message_15 {
            get {
                return ResourceManager.GetString("Sheet_Message_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Sheet_Message_16 {
            get {
                return ResourceManager.GetString("Sheet_Message_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOB Master Fund (UOBMF).
        /// </summary>
        public static string Sheet_Message_2 {
            get {
                return ResourceManager.GetString("Sheet_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investor choice (INVC).
        /// </summary>
        public static string Sheet_Message_3 {
            get {
                return ResourceManager.GetString("Sheet_Message_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMK1.
        /// </summary>
        public static string Sheet_Message_4 {
            get {
                return ResourceManager.GetString("Sheet_Message_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMK1.
        /// </summary>
        public static string Sheet_Message_5 {
            get {
                return ResourceManager.GetString("Sheet_Message_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMK2.
        /// </summary>
        public static string Sheet_Message_6 {
            get {
                return ResourceManager.GetString("Sheet_Message_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMK2.
        /// </summary>
        public static string Sheet_Message_7 {
            get {
                return ResourceManager.GetString("Sheet_Message_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Outlook.
        /// </summary>
        public static string Sheet_Message_8 {
            get {
                return ResourceManager.GetString("Sheet_Message_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESG Investment.
        /// </summary>
        public static string Sheet_Message_9 {
            get {
                return ResourceManager.GetString("Sheet_Message_9", resourceCulture);
            }
        }
    }
}
