//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOB.PVD.CMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UOB.PVD.CMS.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English article.
        /// </summary>
        public static string Article_label_content_en {
            get {
                return ResourceManager.GetString("Article_label_content_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai article.
        /// </summary>
        public static string Article_label_content_th {
            get {
                return ResourceManager.GetString("Article_label_content_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English picture.
        /// </summary>
        public static string Article_label_head_upload_image_en {
            get {
                return ResourceManager.GetString("Article_label_head_upload_image_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai picture.
        /// </summary>
        public static string Article_label_head_upload_image_th {
            get {
                return ResourceManager.GetString("Article_label_head_upload_image_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Article_label_image_en {
            get {
                return ResourceManager.GetString("Article_label_image_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture mobile size.
        /// </summary>
        public static string Article_label_image_mobile_en {
            get {
                return ResourceManager.GetString("Article_label_image_mobile_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture mobile size.
        /// </summary>
        public static string Article_label_image_mobile_th {
            get {
                return ResourceManager.GetString("Article_label_image_mobile_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Article_label_image_th {
            get {
                return ResourceManager.GetString("Article_label_image_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string banner_label_detail {
            get {
                return ResourceManager.GetString("banner_label_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English picture.
        /// </summary>
        public static string banner_label_head_upload_image_en {
            get {
                return ResourceManager.GetString("banner_label_head_upload_image_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recommended size 320 x 240 px.
        /// </summary>
        public static string banner_label_head_upload_image_mobile_th {
            get {
                return ResourceManager.GetString("banner_label_head_upload_image_mobile_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai picture.
        /// </summary>
        public static string banner_label_head_upload_image_th {
            get {
                return ResourceManager.GetString("banner_label_head_upload_image_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปภาษาไทย.
        /// </summary>
        public static string banner_label_image_detail {
            get {
                return ResourceManager.GetString("banner_label_image_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string banner_label_image_en {
            get {
                return ResourceManager.GetString("banner_label_image_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture mobile size.
        /// </summary>
        public static string banner_label_image_mobile_en {
            get {
                return ResourceManager.GetString("banner_label_image_mobile_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture mobile size.
        /// </summary>
        public static string banner_label_image_mobile_th {
            get {
                return ResourceManager.GetString("banner_label_image_mobile_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string banner_label_image_th {
            get {
                return ResourceManager.GetString("banner_label_image_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string banner_label_link {
            get {
                return ResourceManager.GetString("banner_label_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English message.
        /// </summary>
        public static string banner_label_text_en {
            get {
                return ResourceManager.GetString("banner_label_text_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai message.
        /// </summary>
        public static string banner_label_text_th {
            get {
                return ResourceManager.GetString("banner_label_text_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English title.
        /// </summary>
        public static string banner_label_title_en {
            get {
                return ResourceManager.GetString("banner_label_title_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai title.
        /// </summary>
        public static string banner_label_title_th {
            get {
                return ResourceManager.GetString("banner_label_title_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload VDO.
        /// </summary>
        public static string banner_label_upload_vdo {
            get {
                return ResourceManager.GetString("banner_label_upload_vdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VDO.
        /// </summary>
        public static string banner_label_vdo {
            get {
                return ResourceManager.GetString("banner_label_vdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picture.
        /// </summary>
        public static string bannerlist_datatable_col_image {
            get {
                return ResourceManager.GetString("bannerlist_datatable_col_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no..
        /// </summary>
        public static string bannerlist_datatable_col_no {
            get {
                return ResourceManager.GetString("bannerlist_datatable_col_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        public static string bannerlist_datatable_col_status {
            get {
                return ResourceManager.GetString("bannerlist_datatable_col_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English title.
        /// </summary>
        public static string bannerlist_datatable_col_title_en {
            get {
                return ResourceManager.GetString("bannerlist_datatable_col_title_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai title.
        /// </summary>
        public static string bannerlist_datatable_col_title_th {
            get {
                return ResourceManager.GetString("bannerlist_datatable_col_title_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string btn_back {
            get {
                return ResourceManager.GetString("btn_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string btn_clear {
            get {
                return ResourceManager.GetString("btn_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string btn_create {
            get {
                return ResourceManager.GetString("btn_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btn_delete {
            get {
                return ResourceManager.GetString("btn_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string btn_publish {
            get {
                return ResourceManager.GetString("btn_publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btn_save {
            get {
                return ResourceManager.GetString("btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string btn_search {
            get {
                return ResourceManager.GetString("btn_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnPublish.
        /// </summary>
        public static string btn_unpublish {
            get {
                return ResourceManager.GetString("btn_unpublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string btn_upload {
            get {
                return ResourceManager.GetString("btn_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btn_view_detail {
            get {
                return ResourceManager.GetString("btn_view_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete?.
        /// </summary>
        public static string confirm_delete {
            get {
                return ResourceManager.GetString("confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to display this item on website.?.
        /// </summary>
        public static string confirm_publish {
            get {
                return ResourceManager.GetString("confirm_publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to save?.
        /// </summary>
        public static string confirm_save {
            get {
                return ResourceManager.GetString("confirm_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available in table.
        /// </summary>
        public static string Datatable_language_emptyTable {
            get {
                return ResourceManager.GetString("Datatable_language_emptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing _START_ to _END_ of _TOTAL_ entries.
        /// </summary>
        public static string Datatable_language_info {
            get {
                return ResourceManager.GetString("Datatable_language_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing 0 to 0 of 0 entries.
        /// </summary>
        public static string Datatable_language_infoEmpty {
            get {
                return ResourceManager.GetString("Datatable_language_infoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Datatable_language_infoFiltered {
            get {
                return ResourceManager.GetString("Datatable_language_infoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Datatable_language_loadingRecords {
            get {
                return ResourceManager.GetString("Datatable_language_loadingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string Datatable_language_paginate_First {
            get {
                return ResourceManager.GetString("Datatable_language_paginate_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Datatable_language_paginate_Last {
            get {
                return ResourceManager.GetString("Datatable_language_paginate_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Datatable_language_paginate_Next {
            get {
                return ResourceManager.GetString("Datatable_language_paginate_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Datatable_language_paginate_previous {
            get {
                return ResourceManager.GetString("Datatable_language_paginate_previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string Datatable_language_processing {
            get {
                return ResourceManager.GetString("Datatable_language_processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string Datatable_language_thousands {
            get {
                return ResourceManager.GetString("Datatable_language_thousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching records found.
        /// </summary>
        public static string Datatable_language_zeroRecords {
            get {
                return ResourceManager.GetString("Datatable_language_zeroRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Fund_label_detail {
            get {
                return ResourceManager.GetString("Fund_label_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English picture.
        /// </summary>
        public static string Fund_label_image_en {
            get {
                return ResourceManager.GetString("Fund_label_image_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai picture.
        /// </summary>
        public static string Fund_label_image_th {
            get {
                return ResourceManager.GetString("Fund_label_image_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Fund_label_link {
            get {
                return ResourceManager.GetString("Fund_label_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Fund_label_upload_image {
            get {
                return ResourceManager.GetString("Fund_label_upload_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOB Asset Management.
        /// </summary>
        public static string login_project_name {
            get {
                return ResourceManager.GetString("login_project_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string menu_sub_Article {
            get {
                return ResourceManager.GetString("menu_sub_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner.
        /// </summary>
        public static string menu_sub_banner {
            get {
                return ResourceManager.GetString("menu_sub_banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fund.
        /// </summary>
        public static string menu_sub_Fund {
            get {
                return ResourceManager.GetString("menu_sub_Fund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        public static string menu_system_1 {
            get {
                return ResourceManager.GetString("menu_system_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string message_error {
            get {
                return ResourceManager.GetString("message_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recommended size 1920 x 360 px.
        /// </summary>
        public static string upload_imagenormal_size {
            get {
                return ResourceManager.GetString("upload_imagenormal_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Please upload english picture&lt;br/&gt;.
        /// </summary>
        public static string validate_upload_image_en {
            get {
                return ResourceManager.GetString("validate_upload_image_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Please upload thai picture&lt;br/&gt;.
        /// </summary>
        public static string validate_upload_image_th {
            get {
                return ResourceManager.GetString("validate_upload_image_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Please upload VDO&lt;br/&gt;.
        /// </summary>
        public static string validate_upload_vdo {
            get {
                return ResourceManager.GetString("validate_upload_vdo", resourceCulture);
            }
        }
    }
}
